export const HINTS: Record<string, string> = {
  'e4':"Control the center — advance your king's pawn two squares.",
  'e5':"Mirror White and stake your claim in the center.",
  'd4':"Control the center with your queen pawn.",
  'd5':"Challenge White's center immediately.",
  'c4':"The Queen's Gambit — pressure Black's d5 pawn.",
  'c5':"The Sicilian — fight for d4 asymmetrically.",
  'c6':"The Caro-Kann — prepare to strike back at the center.",
  'c3':"Prepare to recapture and open the diagonals.",
  'e6':"Support d5 and prepare bishop development.",
  'e3':"Solidify the center and free the dark-squared bishop.",
  'f4':"The King's Gambit — offer your f-pawn for attacking chances.",
  'f3':"Fortify the center and prepare a kingside pawn advance.",
  'h4':"Threaten h5 to trap the bishop or gain space.",
  'h5':"Gain kingside space — the bishop on g6 is in trouble!",
  'h6':"Prevent Bg5 pinning the knight, or stop h5.",
  'g4':"The King's Gambit accepted — hold on to the pawn!",
  'g5':"Grab the pawn with tempo — but beware White's attack.",
  'a6':"The Najdorf — prepare b5 and prevent Nb5.",
  'b5':"Push Black's bishop back and gain queenside space.",
  'Nf3':"Develop your knight, attacking Black's center.",
  'Nc6':"Develop your knight, defending e5.",
  'Nc3':"Develop your knight toward the center.",
  'Nb3':"Retreat the knight — avoid the e4-e5 fork.",
  'Nbd7':"Develop your second knight to support the center.",
  'Nd7':"Develop the knight, supporting c5 and e5.",
  'Ne5':"The Kieseritzky — centralise aggressively!",
  'Nxe4':"Recapture the pawn with your knight.",
  'Nxd4':"Recapture centrally and control d4.",
  'Nxd5':"Capture the pawn — the Fried Liver sacrifice is imminent!",
  'Nxf7':"The Fried Liver Sacrifice! The king is forced to move.",
  'Nxg4':"Capture the pawn and stay in the game.",
  'Nxf6+':"Capture the knight, giving check.",
  'Ng3':"Retreat the knight and keep the g6 bishop in its sights.",
  'Ng5':"Attack f7! Black must react to this immediate threat.",
  'Nf6':"Develop your knight and counterattack White's e4.",
  'Bc4':"Develop your bishop to c4, eyeing f7.",
  'Bc5':"Develop your bishop, targeting the f2 weakness.",
  'Bb5':"The Ruy Lopez bishop — pressure the c6 knight indirectly.",
  'Bb4+':"Check! Force White to deal with the bishop.",
  'Bb3':"Retreat the bishop to safety on the b3-f7 diagonal.",
  'Bg5':"Pin the knight and pressure the center.",
  'Bg6':"Keep the bishop — it belongs here.",
  'Bf5':"Develop actively before White plays Ng3.",
  'Be7':"Solid development — prepare to castle kingside.",
  'Be6':"Develop the bishop and challenge White's pieces.",
  'Be3':"Develop the bishop and support the d4 outpost.",
  'Bxb2':"Accept the second pawn — White has massive compensation!",
  'Bxd5':"Capture the pawn — open lines for the bishops.",
  'Bxf7+':"Bishop sacrifice! The king is forced out.",
  'Bd3':"Develop the bishop, supporting the center and eyeing h7.",
  'Ba4':"Retreat the bishop — maintain pressure on c6.",
  'O-O':"Castle kingside — your king is safe here.",
  'Kxf7':"The king must capture — it's exposed but the game goes on.",
  'Qf3+':"Queen check! The king has no good retreat.",
  'Qb3+':"Queen storms in — very dangerous for Black.",
  'Qxf6':"Recapture the knight with the queen.",
  'Ke6':"The king marches to the center — very risky!",
  'Re1':"Rook to e1 — support e4 and prepare for action.",
  'Rc1':"Rook to c1 — prepare queenside pressure.",
  'exd4':"Capture the pawn in the center.",
  'exf4':"Accept the King's Gambit pawn.",
  'exd5':"Capture in the center — the Fried Liver begins!",
  'dxe4':"Capture White's e4 pawn.",
  'dxc3':"Accept the second gambit pawn.",
  'cxd4':"Capture in the center.",
  'cxb2':"Grab the second pawn — White has huge compensation.",
};
